using System.Globalization;
using System.Runtime.InteropServices;

namespace SocAutoTask.Localization;

/// <summary>
/// Textos en español e ingles (constitucion §7, RNF-06). Ningun texto va en el XAML ni en el
/// codigo: todo pasa por aqui. Lo usan la aplicacion y el reproductor de los exe compilados.
/// </summary>
public static partial class Loc
{
    internal static readonly Dictionary<string, string> Spanish = new()
    {
        ["AppTitle"] = "sOC AutoTask",
        ["Untitled"] = "Sin título",
        ["UntitledFile"] = "grabacion",

        // --- Barra
        ["Open"] = "Abrir",
        ["OpenTip"] = "Abrir una grabación (.soctask, .rec o un exe compilado con AutoTask). También puedes arrastrarla aquí.",
        ["Save"] = "Guardar",
        ["SaveTip"] = "Guardar la grabación (.soctask)",
        ["SaveAs"] = "Guardar como…",
        ["Record"] = "Grabar",
        ["RecordTip"] = "Grabar el ratón y el teclado ({0})",
        ["StopRecordTip"] = "Parar de grabar ({0})",
        ["Play"] = "Reproducir",
        ["PlayTip"] = "Reproducir ({0}). Parada de emergencia: {1}",
        ["StopPlayTip"] = "Parar ({0})",
        ["StopShort"] = "Parar",
        ["Compile"] = "Compilar",
        ["CompileTip"] = "Crear un .exe que reproduce esta grabación al abrirlo",
        ["Editor"] = "Editar",
        ["EditorTip"] = "Ver y retocar los eventos de la grabación",
        ["Settings"] = "Ajustes",
        ["SettingsTip"] = "Velocidad, repeticiones, atajos, parada de emergencia y ventana",
        ["More"] = "Más",
        ["MoreTip"] = "Recientes, importar, guía, novedades, administrador y acerca de",
        ["ImportRec"] = "Importar .rec…",
        ["OpenDataFolder"] = "Abrir la carpeta de datos",
        ["Guide"] = "Guía de configuración",
        ["WhatsNew"] = "Novedades",
        ["RestartAsAdmin"] = "Reiniciar como administrador",
        ["About"] = "Acerca de",
        ["Exit"] = "Salir",
        ["EscHeld"] = "Esc mantenida {0:0.#} s",
        ["EmergencyNone"] = "ninguna",

        // --- Estado
        ["StatusReady"] = "Listo. Pulsa Grabar o abre una grabación.",
        ["StatusRecording"] = "Grabando · {0} · {1} eventos",
        ["StatusRecorded"] = "Grabados {0} eventos ({1}). Reprodúcelos o guárdalos.",
        ["StatusNothingRecorded"] = "No se ha grabado nada: se conserva la grabación que había.",
        ["StatusReleaseKeys"] = "Suelta las teclas para empezar…",
        ["StatusCountdown"] = "Empieza en {0}…",
        ["StatusPlaying"] = "Reproduciendo · {0} · queda {1} (total {2})",
        ["StatusPlayingContinuous"] = "Reproduciendo · {0} · queda {1} de esta vuelta",
        ["StatusPause"] = "Pausa entre vueltas · {0}",
        ["StatusFinished"] = "Reproducción terminada.",
        ["StatusStopped"] = "Reproducción parada.",
        ["StatusEmergency"] = "Parada de emergencia: se han soltado todas las teclas.",
        ["StatusOpened"] = "Abierta: {0}",
        ["StatusSaved"] = "Guardada: {0}",
        ["StatusCompiled"] = "Compilada: {0}",
        ["StatusEdited"] = "Cambios del editor aplicados (sin guardar).",
        ["StatusRecovered"] = "Recuperada la grabación sin guardar de la versión anterior.",
        ["LoopOf"] = "vuelta {0} de {1}",
        ["LoopContinuous"] = "vuelta {0}",
        ["ScreenChanged"] = "la pantalla no es la de la grabación",
        ["InfoEmpty"] = "Sin grabación cargada.",
        ["InfoLine"] = "{0} · {1} eventos · {2} · {3} · {4}",
        ["RepeatOnceShort"] = "una vez",
        ["RepeatTimesShort"] = "{0} veces",
        ["RepeatContinuousShort"] = "sin fin",
        ["SandboxNoRecord"] = "[SOC_SANDBOX] En modo aislado no se graba.",
        ["SandboxNoPlay"] = "[SOC_SANDBOX] En modo aislado no se reproduce.",

        // --- Avisos
        ["Ok"] = "Aceptar",
        ["Yes"] = "Sí",
        ["Cancel"] = "Cancelar",
        ["Close"] = "Cerrar",
        ["Discard"] = "Descartar",
        ["UnsavedTitle"] = "Cambios sin guardar",
        ["UnsavedText"] = "«{0}» tiene cambios sin guardar. ¿Quieres guardarlos antes de seguir?",
        ["NumberOutOfRange"] = "Escribe un número entero entre {0} y {1}.",
        ["UnexpectedErrorTitle"] = "Algo ha fallado",
        ["UnexpectedErrorText"] = "Ha ocurrido un error inesperado, pero la aplicación sigue abierta. Si vuelve a pasar, envía al autor el fichero {0} desde «Acerca de».",
        ["RecordFailedTitle"] = "No se puede grabar",
        ["RecordFailed"] = "Windows no ha dejado escuchar el ratón y el teclado. Cierra otros programas de macros o de accesibilidad que puedan estar usándolos y vuelve a probar; si sigue, reinicia el PC.",
        ["PlayFailedTitle"] = "No se puede reproducir",
        ["EmergencyFailed"] = "No se ha podido preparar la parada de emergencia, y sin ella no se reproduce por seguridad. Vuelve a probar; si sigue, reinicia el PC.",
        ["ElevatedTitle"] = "Programa de administrador",
        ["ElevatedWhilePlaying"] = "La ventana en primer plano es de un programa que se ejecuta como administrador, y Windows no deja que AutoTask le envíe teclas ni clics. ¿Reiniciar AutoTask como administrador para poder automatizarlo?",
        ["ElevatedWhileRecording"] = "Has usado una ventana de un programa que se ejecuta como administrador: lo que hiciste en ella puede no haberse grabado. ¿Reiniciar AutoTask como administrador?",
        ["RestartFailed"] = "No se ha podido reiniciar como administrador. Cierra AutoTask y ábrelo con el botón derecho › Ejecutar como administrador.",
        ["RunningAsAdmin"] = "como administrador",
        ["HotkeyTitle"] = "Atajos",
        ["HotkeyTaken"] = "Otro programa ya usa {0}. El botón sigue funcionando; elige otro atajo en Ajustes para usarlo desde cualquier sitio.",
        ["HotkeyNeedsModifier"] = "Un atajo necesita Ctrl, Alt, Mayús o Win y una tecla más.",
        ["HotkeysEqual"] = "Grabar y Reproducir no pueden tener el mismo atajo.",

        // --- Ficheros
        ["FilterOpen"] = "Grabaciones (*.soctask;*.rec;*.exe)|*.soctask;*.rec;*.exe|AutoTask (*.soctask)|*.soctask|Otras utilidades de macros (*.rec)|*.rec|Exe compilado con AutoTask (*.exe)|*.exe",
        ["FilterRec"] = "Otras utilidades de macros (*.rec)|*.rec",
        ["FilterSave"] = "Grabación de AutoTask (*.soctask)|*.soctask",
        ["FilterExe"] = "Programa (*.exe)|*.exe",
        ["FileTypeDescription"] = "Grabación de sOC AutoTask",
        ["OpenFailedTitle"] = "No se puede abrir",
        ["OpenFailed"] = "No se ha podido abrir «{0}». {1}",
        ["SaveFailedTitle"] = "No se puede guardar",
        ["SaveFailed"] = "No se ha podido guardar «{0}». {1}",
        ["FormatNotARecording"] = "No es una grabación de AutoTask. Abre un fichero .soctask, un .rec o un exe compilado con AutoTask.",
        ["FormatNewerVersion"] = "Está hecha con una versión más nueva de AutoTask. Actualiza la aplicación para abrirla.",
        ["FormatTruncated"] = "El fichero está incompleto (quizá se cortó al copiarlo o descargarlo). Vuelve a copiarlo desde el original.",
        ["FormatCorrupt"] = "El fichero está dañado o se ha modificado fuera de AutoTask. Usa una copia buena.",
        ["FormatEmpty"] = "La grabación no tiene ningún evento.",
        ["FormatNotARec"] = "No parece una grabación .rec válida. La importación de .rec es experimental: si es de una versión distinta de esa utilidad, puede no entenderse.",
        ["FileNoPermission"] = "No tienes permiso en esa carpeta. Elige otra (por ejemplo, Documentos).",
        ["FileNotFound"] = "El fichero o la carpeta ya no existe. Comprueba la ruta.",
        ["FilePathTooLong"] = "La ruta es demasiado larga. Elige una carpeta más corta.",
        ["FileDiskFull"] = "El disco está lleno. Libera espacio o elige otro disco.",
        ["FileInUse"] = "Otro programa está usando el fichero. Ciérralo y vuelve a probar.",
        ["FileGenericError"] = "Windows no ha dejado leer o escribir el fichero. Prueba con otro nombre o carpeta.",
        ["RecImportedTitle"] = "Importada (experimental)",
        ["RecImported"] = "Se ha importado la grabación .rec. La importación es experimental: revisa que se reproduce bien. La rueda del ratón se importa siempre hacia arriba (el .rec no guarda la dirección). Guárdala como .soctask para conservarla.",

        // --- Compilar
        ["CompileTitle"] = "Compilar a exe",
        ["CompileNoPlayer"] = "Esta compilación de AutoTask no lleva el reproductor para crear exe. Usa la versión publicada.",
        ["CompileOverSelf"] = "No se puede sobrescribir el propio AutoTask. Elige otro nombre.",
        ["CompileDone"] = "Creado «{0}». Al abrirlo reproduce la grabación con su velocidad y repeticiones; para pararlo: {1}.\n\nAviso: algunos antivirus desconfían de los exe nuevos y sin firma que mueven el ratón y el teclado, y pueden bloquearlo. Es seguro: no usa la red, no escribe en el disco ni se instala, y solo repite lo que grabaste.",
        ["CompileFailed"] = "No se ha podido crear «{0}». {1}",

        // --- Editor
        ["EditorTitle"] = "Editor de eventos",
        ["EditDelete"] = "Borrar",
        ["EditDeleteTip"] = "Borrar los eventos elegidos (Supr). Lo de después no se mueve en el tiempo.",
        ["EditTrimStart"] = "Inicio",
        ["EditTrimStartTip"] = "Recortar el inicio: quitar todo lo anterior al evento elegido",
        ["EditTrimEnd"] = "Final",
        ["EditTrimEndTip"] = "Recortar el final: quitar todo lo posterior al evento elegido",
        ["EditSimplify"] = "Simplificar",
        ["EditSimplifyTip"] = "Quitar movimientos del ratón que sobran (sin tocar los clics ni el tiempo total)",
        ["EditSetDelay"] = "Espera",
        ["EditSetDelayTip"] = "Cambiar la espera de los eventos elegidos",
        ["EditScale"] = "Escalar",
        ["EditScaleTip"] = "Multiplicar las esperas (de los elegidos, o de todos si no hay varios elegidos)",
        ["EditInsertWait"] = "Insertar",
        ["EditInsertWaitTip"] = "Insertar una espera antes del evento elegido",
        ["EditUndo"] = "Deshacer",
        ["EditUndoTip"] = "Deshacer el último cambio (Ctrl+Z)",
        ["EditApply"] = "Aplicar los cambios a la grabación",
        ["SimplifyTolerance"] = "Tolerancia (píxeles)",
        ["SimplifyOnlyLast"] = "Dejar solo el último movimiento antes de cada clic",
        ["SimplifyRemoved"] = "{0} movimientos quitados",
        ["InvalidTolerance"] = "La tolerancia es un número de píxeles entre 0 y 500.",
        ["EditorSummary"] = "{0} eventos · {1}",
        ["EditorEmptyResult"] = "La grabación se quedaría sin eventos: no se aplica. Deshaz algún cambio.",
        ["AskDelay"] = "Espera en milisegundos para los {0} eventos elegidos:",
        ["AskScaleAll"] = "Porcentaje para todas las esperas (50 = la mitad, 200 = el doble):",
        ["AskScaleSelected"] = "Porcentaje para las esperas de los {0} eventos elegidos (50 = la mitad, 200 = el doble):",
        ["AskWait"] = "Milisegundos de espera (1000 = 1 segundo):",
        ["ColTime"] = "Instante",
        ["ColDelay"] = "Espera",
        ["ColKind"] = "Tipo",
        ["ColDetail"] = "Detalle",
        ["KindMouseMove"] = "Movimiento",
        ["KindMouseDown"] = "Botón pulsado",
        ["KindMouseUp"] = "Botón soltado",
        ["KindWheel"] = "Rueda",
        ["KindHWheel"] = "Rueda horizontal",
        ["KindKeyDown"] = "Tecla pulsada",
        ["KindKeyUp"] = "Tecla soltada",
        ["KindWait"] = "Espera",
        ["ButtonLeft"] = "izquierdo",
        ["ButtonRight"] = "derecho",
        ["ButtonMiddle"] = "central",
        ["ButtonX1"] = "X1 (atrás)",
        ["ButtonX2"] = "X2 (adelante)",
        ["DetailMove"] = "a {0}, {1}",
        ["DetailButtonDown"] = "{0} en {1}, {2}",
        ["DetailButtonUp"] = "{0} en {1}, {2}",
        ["DetailWheel"] = "{0} en {1}, {2}",
        ["DetailWait"] = "{0}",

        // --- Ajustes
        ["SettingsTitle"] = "Ajustes",
        ["PlaybackTitle"] = "Reproducción",
        ["PlaybackHint"] = "Se guarda con la grabación; las nuevas empiezan con estos valores.",
        ["SpeedLabel"] = "Velocidad",
        ["CustomSpeed"] = "Personalizada",
        ["CustomSpeedTip"] = "Velocidad personalizada, de 0,1 a 1000",
        ["RepeatLabel"] = "Repetir",
        ["RepeatOnce"] = "Una vez",
        ["RepeatTimes"] = "Este número de veces:",
        ["RepeatContinuous"] = "Sin fin, hasta que la pares",
        ["PauseLabel"] = "Pausa entre repeticiones (segundos)",
        ["CountdownLabel"] = "Cuenta atrás antes de empezar (segundos, 0 a 10)",
        ["InvalidSpeed"] = "La velocidad personalizada es un número entre 0,1 y 1000.",
        ["InvalidTimes"] = "El número de veces es un entero entre 1 y 100000.",
        ["InvalidPause"] = "La pausa entre repeticiones es un número de segundos entre 0 y 3600.",
        ["InvalidCountdown"] = "La cuenta atrás es un número entero de segundos entre 0 y 10.",
        ["InvalidEscapeHold"] = "El tiempo de Esc mantenida es un número de segundos entre 0,2 y 10.",
        ["HotkeysTitle"] = "Atajos y parada de emergencia",
        ["HotkeysHint"] = "Haz clic en la casilla y pulsa la combinación. Funcionan desde cualquier programa; el atajo no se graba.",
        ["RecordHotkeyLabel"] = "Grabar / parar de grabar",
        ["PlayHotkeyLabel"] = "Reproducir / parar",
        ["EmergencyTitle"] = "Parada de emergencia",
        ["EmergencyPause"] = "Tecla Pausa / Inter",
        ["EmergencyScrollLock"] = "Tecla Bloq Despl",
        ["EmergencyEscape"] = "Esc mantenida durante",
        ["Seconds"] = "segundos",
        ["EmergencyHint"] = "Para la reproducción al momento y suelta todas las teclas y botones. Solo cuentan las teclas que pulsas tú, no las de la grabación.",
        ["EmergencyNoneConfirm"] = "Sin ninguna tecla de emergencia solo podrás parar con el atajo o el botón. ¿Seguro?",
        ["RecordingTitle"] = "Qué se graba",
        ["RecordKeyboard"] = "Grabar el teclado",
        ["RecordKeyboardWarning"] = "Una grabación guarda todo lo que tecleas mientras graba, contraseñas incluidas, y queda en el fichero o en el exe que compiles. No grabes contraseñas, o quita el teclado y graba solo el ratón.",
        ["RecordMoves"] = "Grabar los movimientos del ratón (si no, solo clics y rueda)",
        ["ElevationHint"] = "AutoTask solo actúa sobre lo que hay en pantalla, como si fueras tú. Para automatizar programas que se ejecutan como administrador, reinícialo como administrador (menú Más). Algunos juegos no aceptan teclas ni clics simulados.",
        ["WindowTitle"] = "Ventana",
        ["AlwaysOnTop"] = "Siempre encima de las demás ventanas",
        ["ShowLabels"] = "Mostrar el texto debajo de los iconos",
        ["TrayOnMinimize"] = "Al minimizar, al área de notificación (junto al reloj)",
        ["ThemeLabel"] = "Tema",
        ["ThemeSystem"] = "El de Windows",
        ["ThemeLight"] = "Claro",
        ["ThemeDark"] = "Oscuro",
        ["LanguageTitle"] = "Idioma",
        ["LanguageHint"] = "El idioma cambia al momento.",
        ["FilesTitle"] = "Ficheros",
        ["AssociateFiles"] = "Abrir los ficheros .soctask con AutoTask (doble clic en el Explorador)",
        ["AssociateHint"] = "Solo para tu usuario de Windows. Se puede quitar cuando quieras.",
        ["AssociatePackaged"] = "Instalada desde la Microsoft Store o el paquete MSIX: la asociación la pone el propio paquete.",
        ["AssociateFailed"] = "No se ha podido cambiar la asociación de .soctask. Vuelve a probar; si sigue, hazlo desde Configuración de Windows › Aplicaciones predeterminadas.",
        ["DataFolder"] = "Ajustes y registro en {0}",
        ["DataFolderPortable"] = "Modo portátil (hay un portable.ini): ajustes y registro en {0}",

        // --- Bandeja
        ["TrayOpen"] = "Abrir",
        ["TrayRecord"] = "Grabar / parar",
        ["TrayPlay"] = "Reproducir / parar",
        ["TrayExit"] = "Salir",

        // --- Guia
        ["GuideTitle"] = "Guía de configuración",
        ["GuideStep"] = "Paso {0} de {1}",
        ["GuideBack"] = "Anterior",
        ["GuideNext"] = "Siguiente",
        ["GuideDone"] = "Terminar",
        ["GuideOpenSettings"] = "Abrir Ajustes",
        ["GuideAssociate"] = "Asociar .soctask",
        ["StepDone"] = "Hecho",
        ["StepPending"] = "Pendiente",
        ["StepOptional"] = "Opcional",
        ["GuideHotkeysTitle"] = "Atajos globales",
        ["GuideHotkeysText"] = "Con {0} empiezas y paras de grabar, y con {1} reproduces y paras, desde cualquier programa. Si otro programa ya usa alguno, elige otro en Ajustes.",
        ["GuideEmergencyTitle"] = "Parada de emergencia",
        ["GuideEmergencyText"] = "Si una reproducción se desmadra, pulsa Pausa, Bloq Despl o mantén Esc un segundo: se para al momento y se sueltan todas las teclas. Deja al menos una activada.",
        ["GuidePrivacyTitle"] = "Lo que se graba",
        ["GuidePrivacyText"] = "Una grabación guarda todo lo que tecleas mientras graba, contraseñas incluidas. Si solo necesitas el ratón, quita «Grabar el teclado» en Ajustes. Nada sale de tu PC: AutoTask no usa la red.",
        ["GuideFilesTitle"] = "Abrir grabaciones con doble clic",
        ["GuideFilesText"] = "Asocia los ficheros .soctask con AutoTask para abrirlos con doble clic desde el Explorador. Solo afecta a tu usuario.",
        ["GuideAdminTitle"] = "Programas de administrador",
        ["GuideAdminText"] = "Windows no deja que un programa normal envíe teclas o clics a otro que se ejecuta como administrador. Si quieres automatizar uno así, reinicia AutoTask como administrador.",
        ["GuideTryTitle"] = "Pruébalo",
        ["GuideTryText"] = "Pulsa Grabar, haz algo (por ejemplo, escribe en el Bloc de notas), pulsa Parar y luego Reproducir. Con Compilar la conviertes en un .exe y con Editar la retocas.",

        // --- Acerca de
        ["AboutDescription"] = "Graba lo que haces con el ratón y el teclado y lo repite cuando quieras: más rápido, en bucle o como un .exe.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contacto",
        ["WriteAuthor"] = "Escribir al autor",
        ["ContactHint"] = "Sugerencias, fallos e ideas: todo se lee.",
        ["ContactFailed"] = "No hay ningún programa de correo configurado. Escribe a jsoladelarosa@gmail.com.",
        ["Privacy"] = "Privacidad",
        ["PrivacyText"] = "Las grabaciones y los ajustes se guardan solo en tu PC. AutoTask no usa la red: no envía nada a ninguna parte. Sin cuenta, sin anuncios, sin rastreadores, sin analítica.",
        ["License"] = "Licencia",
        ["LicenseText"] = "Software libre bajo licencia MIT. No usa componentes de terceros: solo .NET y Windows. Los detalles, en THIRD-PARTY-NOTICES.md del repositorio.",
        ["LicenseLine"] = "MIT License · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Aviso legal",
        ["LegalText1"] = "Este software se proporciona «tal cual», sin garantía de ningún tipo, expresa o implícita.",
        ["LegalText2"] = "En ningún caso los autores serán responsables de reclamaciones, daños u otras responsabilidades derivadas del uso de este software. Una macro repite lo que grabaste aunque la pantalla haya cambiado: úsala con cuidado.",
        ["WarningText"] = "Úsalo bajo tu propia responsabilidad",

        // --- Reproductor de los exe compilados
        ["PlayerTitle"] = "Reproductor de sOC AutoTask",
        ["PlayerNoRecording"] = "Este programa no lleva ninguna grabación dentro. Vuelve a compilarlo desde AutoTask.",
        ["PlayerBadRecording"] = "La grabación de este programa no se puede usar. {0}",
        ["PlayerHookFailed"] = "No se ha podido preparar la parada de emergencia, y sin ella no se reproduce por seguridad. Vuelve a probar.",

        // --- Teclas (las que no se llaman igual)
        ["Key_Shift"] = "Mayús",
        ["Key_LShift"] = "Mayús izq.",
        ["Key_RShift"] = "Mayús der.",
        ["Key_LCtrl"] = "Ctrl izq.",
        ["Key_RCtrl"] = "Ctrl der.",
        ["Key_LAlt"] = "Alt",
        ["Key_RAlt"] = "Alt Gr",
        ["Key_LWin"] = "Windows",
        ["Key_RWin"] = "Windows der.",
        ["Key_Enter"] = "Intro",
        ["Key_Space"] = "Espacio",
        ["Key_Back"] = "Retroceso",
        ["Key_Delete"] = "Supr",
        ["Key_Insert"] = "Insert",
        ["Key_Pause"] = "Pausa",
        ["Key_ScrollLock"] = "Bloq Despl",
        ["Key_CapsLock"] = "Bloq Mayús",
        ["Key_NumLock"] = "Bloq Num",
        ["Key_Left"] = "Flecha izquierda",
        ["Key_Right"] = "Flecha derecha",
        ["Key_Up"] = "Flecha arriba",
        ["Key_Down"] = "Flecha abajo",
        ["Key_PageUp"] = "RePág",
        ["Key_PageDown"] = "AvPág",
        ["Key_Home"] = "Inicio",
        ["Key_End"] = "Fin",
        ["Key_PrintScreen"] = "Impr Pant",
        ["Key_Apps"] = "Menú",
    };

    internal static readonly Dictionary<string, string> English = new()
    {
        ["AppTitle"] = "sOC AutoTask",
        ["Untitled"] = "Untitled",
        ["UntitledFile"] = "recording",

        ["Open"] = "Open",
        ["OpenTip"] = "Open a recording (.soctask, .rec or an exe compiled with AutoTask). You can also drop it here.",
        ["Save"] = "Save",
        ["SaveTip"] = "Save the recording (.soctask)",
        ["SaveAs"] = "Save as…",
        ["Record"] = "Record",
        ["RecordTip"] = "Record mouse and keyboard ({0})",
        ["StopRecordTip"] = "Stop recording ({0})",
        ["Play"] = "Play",
        ["PlayTip"] = "Play ({0}). Emergency stop: {1}",
        ["StopPlayTip"] = "Stop ({0})",
        ["StopShort"] = "Stop",
        ["Compile"] = "Compile",
        ["CompileTip"] = "Create an .exe that plays this recording when opened",
        ["Editor"] = "Edit",
        ["EditorTip"] = "View and tweak the recording's events",
        ["Settings"] = "Settings",
        ["SettingsTip"] = "Speed, repeats, shortcuts, emergency stop and window",
        ["More"] = "More",
        ["MoreTip"] = "Recent files, import, guide, what's new, administrator and about",
        ["ImportRec"] = "Import .rec…",
        ["OpenDataFolder"] = "Open the data folder",
        ["Guide"] = "Setup guide",
        ["WhatsNew"] = "What's new",
        ["RestartAsAdmin"] = "Restart as administrator",
        ["About"] = "About",
        ["Exit"] = "Exit",
        ["EscHeld"] = "Esc held {0:0.#} s",
        ["EmergencyNone"] = "none",

        ["StatusReady"] = "Ready. Press Record or open a recording.",
        ["StatusRecording"] = "Recording · {0} · {1} events",
        ["StatusRecorded"] = "Recorded {0} events ({1}). Play or save them.",
        ["StatusNothingRecorded"] = "Nothing was recorded: the previous recording is kept.",
        ["StatusReleaseKeys"] = "Release the keys to start…",
        ["StatusCountdown"] = "Starting in {0}…",
        ["StatusPlaying"] = "Playing · {0} · {1} left (total {2})",
        ["StatusPlayingContinuous"] = "Playing · {0} · {1} left in this loop",
        ["StatusPause"] = "Pause between loops · {0}",
        ["StatusFinished"] = "Playback finished.",
        ["StatusStopped"] = "Playback stopped.",
        ["StatusEmergency"] = "Emergency stop: all keys have been released.",
        ["StatusOpened"] = "Opened: {0}",
        ["StatusSaved"] = "Saved: {0}",
        ["StatusCompiled"] = "Compiled: {0}",
        ["StatusEdited"] = "Editor changes applied (not saved).",
        ["StatusRecovered"] = "Recovered the unsaved recording from the previous version.",
        ["LoopOf"] = "loop {0} of {1}",
        ["LoopContinuous"] = "loop {0}",
        ["ScreenChanged"] = "the screen differs from the recording's",
        ["InfoEmpty"] = "No recording loaded.",
        ["InfoLine"] = "{0} · {1} events · {2} · {3} · {4}",
        ["RepeatOnceShort"] = "once",
        ["RepeatTimesShort"] = "{0} times",
        ["RepeatContinuousShort"] = "forever",
        ["SandboxNoRecord"] = "[SOC_SANDBOX] No recording in sandbox mode.",
        ["SandboxNoPlay"] = "[SOC_SANDBOX] No playback in sandbox mode.",

        ["Ok"] = "OK",
        ["Yes"] = "Yes",
        ["Cancel"] = "Cancel",
        ["Close"] = "Close",
        ["Discard"] = "Discard",
        ["UnsavedTitle"] = "Unsaved changes",
        ["UnsavedText"] = "\"{0}\" has unsaved changes. Do you want to save them first?",
        ["NumberOutOfRange"] = "Type a whole number between {0} and {1}.",
        ["UnexpectedErrorTitle"] = "Something went wrong",
        ["UnexpectedErrorText"] = "An unexpected error happened, but the app is still open. If it happens again, send the author the file {0} from About.",
        ["RecordFailedTitle"] = "Can't record",
        ["RecordFailed"] = "Windows didn't allow listening to the mouse and keyboard. Close other macro or accessibility programs that may be using them and try again; if it persists, restart the PC.",
        ["PlayFailedTitle"] = "Can't play",
        ["EmergencyFailed"] = "The emergency stop couldn't be set up, and for safety nothing is played without it. Try again; if it persists, restart the PC.",
        ["ElevatedTitle"] = "Administrator program",
        ["ElevatedWhilePlaying"] = "The foreground window belongs to a program running as administrator, and Windows doesn't let AutoTask send it keys or clicks. Restart AutoTask as administrator to automate it?",
        ["ElevatedWhileRecording"] = "You used a window of a program running as administrator: what you did there may not have been recorded. Restart AutoTask as administrator?",
        ["RestartFailed"] = "Couldn't restart as administrator. Close AutoTask and open it with right-click › Run as administrator.",
        ["RunningAsAdmin"] = "as administrator",
        ["HotkeyTitle"] = "Shortcuts",
        ["HotkeyTaken"] = "Another program already uses {0}. The button still works; choose another shortcut in Settings to use it from anywhere.",
        ["HotkeyNeedsModifier"] = "A shortcut needs Ctrl, Alt, Shift or Win plus one more key.",
        ["HotkeysEqual"] = "Record and Play can't have the same shortcut.",

        ["FilterOpen"] = "Recordings (*.soctask;*.rec;*.exe)|*.soctask;*.rec;*.exe|AutoTask (*.soctask)|*.soctask|Other macro tools (*.rec)|*.rec|Exe compiled with AutoTask (*.exe)|*.exe",
        ["FilterRec"] = "Other macro tools (*.rec)|*.rec",
        ["FilterSave"] = "AutoTask recording (*.soctask)|*.soctask",
        ["FilterExe"] = "Program (*.exe)|*.exe",
        ["FileTypeDescription"] = "sOC AutoTask recording",
        ["OpenFailedTitle"] = "Can't open",
        ["OpenFailed"] = "Couldn't open \"{0}\". {1}",
        ["SaveFailedTitle"] = "Can't save",
        ["SaveFailed"] = "Couldn't save \"{0}\". {1}",
        ["FormatNotARecording"] = "It isn't an AutoTask recording. Open a .soctask file, a .rec file or an exe compiled with AutoTask.",
        ["FormatNewerVersion"] = "It was made with a newer version of AutoTask. Update the app to open it.",
        ["FormatTruncated"] = "The file is incomplete (maybe it was cut off while copying or downloading). Copy it again from the original.",
        ["FormatCorrupt"] = "The file is damaged or was changed outside AutoTask. Use a good copy.",
        ["FormatEmpty"] = "The recording has no events.",
        ["FormatNotARec"] = "It doesn't look like a valid .rec recording. Importing .rec is experimental: files from a different version of that tool may not be understood.",
        ["FileNoPermission"] = "You don't have permission in that folder. Choose another one (for example, Documents).",
        ["FileNotFound"] = "The file or folder no longer exists. Check the path.",
        ["FilePathTooLong"] = "The path is too long. Choose a shorter folder.",
        ["FileDiskFull"] = "The disk is full. Free some space or choose another disk.",
        ["FileInUse"] = "Another program is using the file. Close it and try again.",
        ["FileGenericError"] = "Windows didn't allow reading or writing the file. Try another name or folder.",
        ["RecImportedTitle"] = "Imported (experimental)",
        ["RecImported"] = "The .rec recording was imported. Importing is experimental: check that it plays back correctly. Mouse wheel turns are always imported upwards (.rec doesn't store the direction). Save it as .soctask to keep it.",

        ["CompileTitle"] = "Compile to exe",
        ["CompileNoPlayer"] = "This build of AutoTask doesn't include the player needed to create exes. Use the released version.",
        ["CompileOverSelf"] = "AutoTask itself can't be overwritten. Choose another name.",
        ["CompileDone"] = "Created \"{0}\". When opened it plays the recording with its speed and repeats; to stop it: {1}.\n\nNote: some antivirus programs distrust new, unsigned exes that move the mouse and keyboard, and may block it. It is safe: it doesn't use the network, doesn't write to disk or install anything, and only repeats what you recorded.",
        ["CompileFailed"] = "Couldn't create \"{0}\". {1}",

        ["EditorTitle"] = "Event editor",
        ["EditDelete"] = "Delete",
        ["EditDeleteTip"] = "Delete the selected events (Del). What comes after doesn't move in time.",
        ["EditTrimStart"] = "Start",
        ["EditTrimStartTip"] = "Trim the start: remove everything before the selected event",
        ["EditTrimEnd"] = "End",
        ["EditTrimEndTip"] = "Trim the end: remove everything after the selected event",
        ["EditSimplify"] = "Simplify",
        ["EditSimplifyTip"] = "Remove unneeded mouse moves (clicks and total time stay the same)",
        ["EditSetDelay"] = "Wait",
        ["EditSetDelayTip"] = "Change the wait of the selected events",
        ["EditScale"] = "Scale",
        ["EditScaleTip"] = "Multiply the waits (of the selected events, or of all if several aren't selected)",
        ["EditInsertWait"] = "Insert",
        ["EditInsertWaitTip"] = "Insert a wait before the selected event",
        ["EditUndo"] = "Undo",
        ["EditUndoTip"] = "Undo the last change (Ctrl+Z)",
        ["EditApply"] = "Apply the changes to the recording",
        ["SimplifyTolerance"] = "Tolerance (pixels)",
        ["SimplifyOnlyLast"] = "Keep only the last move before each click",
        ["SimplifyRemoved"] = "{0} moves removed",
        ["InvalidTolerance"] = "The tolerance is a number of pixels between 0 and 500.",
        ["EditorSummary"] = "{0} events · {1}",
        ["EditorEmptyResult"] = "The recording would have no events left: not applied. Undo some change.",
        ["AskDelay"] = "Wait in milliseconds for the {0} selected events:",
        ["AskScaleAll"] = "Percentage for all waits (50 = half, 200 = double):",
        ["AskScaleSelected"] = "Percentage for the waits of the {0} selected events (50 = half, 200 = double):",
        ["AskWait"] = "Milliseconds to wait (1000 = 1 second):",
        ["ColTime"] = "Time",
        ["ColDelay"] = "Wait",
        ["ColKind"] = "Type",
        ["ColDetail"] = "Detail",
        ["KindMouseMove"] = "Move",
        ["KindMouseDown"] = "Button down",
        ["KindMouseUp"] = "Button up",
        ["KindWheel"] = "Wheel",
        ["KindHWheel"] = "Horizontal wheel",
        ["KindKeyDown"] = "Key down",
        ["KindKeyUp"] = "Key up",
        ["KindWait"] = "Wait",
        ["ButtonLeft"] = "left",
        ["ButtonRight"] = "right",
        ["ButtonMiddle"] = "middle",
        ["ButtonX1"] = "X1 (back)",
        ["ButtonX2"] = "X2 (forward)",
        ["DetailMove"] = "to {0}, {1}",
        ["DetailButtonDown"] = "{0} at {1}, {2}",
        ["DetailButtonUp"] = "{0} at {1}, {2}",
        ["DetailWheel"] = "{0} at {1}, {2}",
        ["DetailWait"] = "{0}",

        ["SettingsTitle"] = "Settings",
        ["PlaybackTitle"] = "Playback",
        ["PlaybackHint"] = "Saved with the recording; new recordings start with these values.",
        ["SpeedLabel"] = "Speed",
        ["CustomSpeed"] = "Custom",
        ["CustomSpeedTip"] = "Custom speed, from 0.1 to 1000",
        ["RepeatLabel"] = "Repeat",
        ["RepeatOnce"] = "Once",
        ["RepeatTimes"] = "This number of times:",
        ["RepeatContinuous"] = "Forever, until you stop it",
        ["PauseLabel"] = "Pause between repeats (seconds)",
        ["CountdownLabel"] = "Countdown before starting (seconds, 0 to 10)",
        ["InvalidSpeed"] = "The custom speed is a number between 0.1 and 1000.",
        ["InvalidTimes"] = "The number of times is a whole number between 1 and 100000.",
        ["InvalidPause"] = "The pause between repeats is a number of seconds between 0 and 3600.",
        ["InvalidCountdown"] = "The countdown is a whole number of seconds between 0 and 10.",
        ["InvalidEscapeHold"] = "The Esc hold time is a number of seconds between 0.2 and 10.",
        ["HotkeysTitle"] = "Shortcuts and emergency stop",
        ["HotkeysHint"] = "Click the box and press the combination. They work from any program; the shortcut isn't recorded.",
        ["RecordHotkeyLabel"] = "Record / stop recording",
        ["PlayHotkeyLabel"] = "Play / stop",
        ["EmergencyTitle"] = "Emergency stop",
        ["EmergencyPause"] = "Pause / Break key",
        ["EmergencyScrollLock"] = "Scroll Lock key",
        ["EmergencyEscape"] = "Esc held for",
        ["Seconds"] = "seconds",
        ["EmergencyHint"] = "Stops playback at once and releases every key and button. Only keys you press count, not the ones in the recording.",
        ["EmergencyNoneConfirm"] = "Without any emergency key you can only stop with the shortcut or the button. Are you sure?",
        ["RecordingTitle"] = "What is recorded",
        ["RecordKeyboard"] = "Record the keyboard",
        ["RecordKeyboardWarning"] = "A recording stores everything you type while recording, passwords included, and it stays in the file or in any exe you compile. Don't record passwords, or turn the keyboard off and record only the mouse.",
        ["RecordMoves"] = "Record mouse moves (otherwise only clicks and wheel)",
        ["ElevationHint"] = "AutoTask only acts on what is on screen, as if it were you. To automate programs running as administrator, restart it as administrator (More menu). Some games don't accept simulated keys or clicks.",
        ["WindowTitle"] = "Window",
        ["AlwaysOnTop"] = "Always on top of other windows",
        ["ShowLabels"] = "Show the text under the icons",
        ["TrayOnMinimize"] = "When minimized, go to the notification area (next to the clock)",
        ["ThemeLabel"] = "Theme",
        ["ThemeSystem"] = "Same as Windows",
        ["ThemeLight"] = "Light",
        ["ThemeDark"] = "Dark",
        ["LanguageTitle"] = "Language",
        ["LanguageHint"] = "The language changes right away.",
        ["FilesTitle"] = "Files",
        ["AssociateFiles"] = "Open .soctask files with AutoTask (double-click in File Explorer)",
        ["AssociateHint"] = "Only for your Windows user. It can be removed at any time.",
        ["AssociatePackaged"] = "Installed from the Microsoft Store or the MSIX package: the package sets the association itself.",
        ["AssociateFailed"] = "Couldn't change the .soctask association. Try again; if it persists, do it from Windows Settings › Default apps.",
        ["DataFolder"] = "Settings and log in {0}",
        ["DataFolderPortable"] = "Portable mode (there is a portable.ini): settings and log in {0}",

        ["TrayOpen"] = "Open",
        ["TrayRecord"] = "Record / stop",
        ["TrayPlay"] = "Play / stop",
        ["TrayExit"] = "Exit",

        ["GuideTitle"] = "Setup guide",
        ["GuideStep"] = "Step {0} of {1}",
        ["GuideBack"] = "Back",
        ["GuideNext"] = "Next",
        ["GuideDone"] = "Finish",
        ["GuideOpenSettings"] = "Open Settings",
        ["GuideAssociate"] = "Associate .soctask",
        ["StepDone"] = "Done",
        ["StepPending"] = "Pending",
        ["StepOptional"] = "Optional",
        ["GuideHotkeysTitle"] = "Global shortcuts",
        ["GuideHotkeysText"] = "{0} starts and stops recording, and {1} plays and stops, from any program. If another program already uses one, choose another in Settings.",
        ["GuideEmergencyTitle"] = "Emergency stop",
        ["GuideEmergencyText"] = "If a playback gets out of hand, press Pause, Scroll Lock or hold Esc for a second: it stops at once and every key is released. Keep at least one enabled.",
        ["GuidePrivacyTitle"] = "What gets recorded",
        ["GuidePrivacyText"] = "A recording stores everything you type while recording, passwords included. If you only need the mouse, turn off \"Record the keyboard\" in Settings. Nothing leaves your PC: AutoTask doesn't use the network.",
        ["GuideFilesTitle"] = "Open recordings with a double-click",
        ["GuideFilesText"] = "Associate .soctask files with AutoTask to open them with a double-click in File Explorer. It only affects your user.",
        ["GuideAdminTitle"] = "Administrator programs",
        ["GuideAdminText"] = "Windows doesn't let a normal program send keys or clicks to one running as administrator. To automate one of those, restart AutoTask as administrator.",
        ["GuideTryTitle"] = "Try it",
        ["GuideTryText"] = "Press Record, do something (for example, type in Notepad), press Stop and then Play. Compile turns it into an .exe and Edit lets you tweak it.",

        ["AboutDescription"] = "Records what you do with the mouse and keyboard and repeats it whenever you want: faster, in a loop or as an .exe.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contact",
        ["WriteAuthor"] = "Write to the author",
        ["ContactHint"] = "Suggestions, bugs and ideas: all of it gets read.",
        ["ContactFailed"] = "No email program is set up. Write to jsoladelarosa@gmail.com.",
        ["Privacy"] = "Privacy",
        ["PrivacyText"] = "Recordings and settings are stored only on your PC. AutoTask doesn't use the network: it sends nothing anywhere. No account, no ads, no trackers, no analytics.",
        ["License"] = "License",
        ["LicenseText"] = "Free software under the MIT licence. It uses no third-party components: only .NET and Windows. Details in THIRD-PARTY-NOTICES.md in the repository.",
        ["LicenseLine"] = "MIT License · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Legal notice",
        ["LegalText1"] = "This software is provided \"as is\", without warranty of any kind, express or implied.",
        ["LegalText2"] = "In no event shall the authors be liable for any claim, damages or other liability arising from the use of this software. A macro repeats what you recorded even if the screen has changed: use it with care.",
        ["WarningText"] = "Use at your own risk",

        ["PlayerTitle"] = "sOC AutoTask player",
        ["PlayerNoRecording"] = "This program has no recording inside. Compile it again from AutoTask.",
        ["PlayerBadRecording"] = "This program's recording can't be used. {0}",
        ["PlayerHookFailed"] = "The emergency stop couldn't be set up, and for safety nothing is played without it. Try again.",

        ["Key_Shift"] = "Shift",
        ["Key_LShift"] = "Left Shift",
        ["Key_RShift"] = "Right Shift",
        ["Key_LCtrl"] = "Left Ctrl",
        ["Key_RCtrl"] = "Right Ctrl",
        ["Key_LAlt"] = "Alt",
        ["Key_RAlt"] = "Alt Gr",
        ["Key_LWin"] = "Windows",
        ["Key_RWin"] = "Right Windows",
        ["Key_Enter"] = "Enter",
        ["Key_Space"] = "Space",
        ["Key_Back"] = "Backspace",
        ["Key_Delete"] = "Delete",
        ["Key_Insert"] = "Insert",
        ["Key_Pause"] = "Pause",
        ["Key_ScrollLock"] = "Scroll Lock",
        ["Key_CapsLock"] = "Caps Lock",
        ["Key_NumLock"] = "Num Lock",
        ["Key_Left"] = "Left arrow",
        ["Key_Right"] = "Right arrow",
        ["Key_Up"] = "Up arrow",
        ["Key_Down"] = "Down arrow",
        ["Key_PageUp"] = "Page Up",
        ["Key_PageDown"] = "Page Down",
        ["Key_Home"] = "Home",
        ["Key_End"] = "End",
        ["Key_PrintScreen"] = "Print Screen",
        ["Key_Apps"] = "Menu",
    };

    public static string Language { get; private set; } = "en";

    public static CultureInfo Culture { get; private set; } = MakeCulture("en-US");

    public static event Action? LanguageChanged;

    /// <summary>Cambia el idioma («es» o «en»; cualquier otro, ingles) y avisa a quien escuche.</summary>
    public static void Use(string language)
    {
        var next = language == "es" ? "es" : "en";
        if (next == Language)
            return;
        Language = next;
        Culture = MakeCulture(next == "es" ? "es-ES" : "en-US");
        LanguageChanged?.Invoke();
    }

    /// <summary>El idioma de la interfaz de Windows (sirve tambien en el reproductor, sin culturas).</summary>
    public static string SystemLanguage()
    {
        try
        {
            return (GetUserDefaultUILanguage() & 0x3FF) == 0x0A ? "es" : "en";
        }
        catch (EntryPointNotFoundException)
        {
            return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "es" ? "es" : "en";
        }
    }

    public static string Get(string key)
    {
        var table = Language == "es" ? Spanish : English;
        return table.TryGetValue(key, out var value) ? value
            : English.TryGetValue(key, out var fallback) ? fallback
            : string.Empty;
    }

    public static string Format(string key, params object[] args) => string.Format(Culture, Get(key), args);

    private static CultureInfo MakeCulture(string name)
    {
        try
        {
            return CultureInfo.GetCultureInfo(name);
        }
        catch (CultureNotFoundException)
        {
            return CultureInfo.InvariantCulture;
        }
    }

    [LibraryImport("kernel32.dll")]
    private static partial ushort GetUserDefaultUILanguage();
}
